name = "evan-portfolio"
compatibility_date = "2025-01-01"

[site]
bucket = "./public"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "directory"
dir = "./public"